name: recogenie_restaurant
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cherry_toast: ^1.13.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  cached_network_image: ^3.3.1
  injectable: ^2.3.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8


flutter:
  uses-material-design: true
